name: Say hello
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run a container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "Masqueey"

      - name: Hello printed at time
        run: echo "Hello was printed at ${{ steps.hello-action.outputs.time }}."
